"use client";

import { useAuth } from "@/hooks/use-auth";
import { api } from "@/lib/api";
import { useEffect, useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Loader2, Banknote, ChevronLeft, ChevronRight, Download } from "lucide-react";
import { toast } from "sonner";
import { jsPDF } from "jspdf";

export default function PaymentsPage() {
  const { getAccessToken } = useAuth();
  const [payments, setPayments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);

  const load = async (p: number) => {
    setLoading(true);
    try {
      const token = await getAccessToken();
      if (!token) return;
      const res = await api.me.payments(token, p);
      setPayments(res.payments || []);
      setTotal(res.total || res.payments?.length || 0);
    } catch {
      toast.error("Failed to load payments");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(page); }, [getAccessToken, page]);

  const downloadPayslip = async (paymentId: string) => {
    try {
      const token = await getAccessToken();
      if (!token) return;
      const res = await api.me.payslip(token, paymentId);
      const s = res.payslip;

      const doc = new jsPDF();
      const w = doc.internal.pageSize.getWidth();

      // Header
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text("PAYSLIP", w / 2, 28, { align: "center" });

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100);
      doc.text(s.organization.name, w / 2, 36, { align: "center" });

      // Divider
      doc.setDrawColor(220);
      doc.line(20, 42, w - 20, 42);

      // Details
      doc.setTextColor(60);
      doc.setFontSize(10);
      let y = 54;
      const left = 24;
      const right = 90;

      const row = (label: string, value: string) => {
        doc.setFont("helvetica", "normal");
        doc.setTextColor(120);
        doc.text(label, left, y);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(30);
        doc.text(value, right, y);
        y += 10;
      };

      row("Employee", s.employee.name);
      row("Email", s.employee.email || "—");
      row("Type", s.employee.type === "FULL_TIME" ? "Full-time" : "Contractor");
      row("Pay Frequency", s.employee.frequency);

      y += 4;
      doc.setDrawColor(240);
      doc.line(20, y, w - 20, y);
      y += 12;

      row("Pay Date", new Date(s.date).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" }));
      row("Status", s.status);
      if (s.txId) row("Transaction ID", s.txId.slice(0, 20) + "...");

      y += 4;
      doc.setDrawColor(240);
      doc.line(20, y, w - 20, y);
      y += 14;

      // Amount
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(120);
      doc.text("Net Payment", left, y);
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(20);
      doc.text(`$${parseFloat(s.amount).toFixed(2)} USDC`, right, y);

      y += 20;
      doc.setDrawColor(220);
      doc.line(20, y, w - 20, y);

      // Footer
      y += 12;
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(160);
      doc.text("Generated by Warden — Private payroll on Base", w / 2, y, { align: "center" });
      doc.text("This payslip was generated from a zero-knowledge private transfer.", w / 2, y + 6, { align: "center" });

      doc.save(`payslip-${new Date(s.date).toISOString().split("T")[0]}.pdf`);
      toast.success("Payslip downloaded!");
    } catch {
      toast.error("Failed to generate payslip");
    }
  };

  const totalPages = Math.max(1, Math.ceil(total / 20));

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Payments</h1>
        <p className="text-muted-foreground mt-1">Your payment history</p>
      </div>

      <Card>
        <CardContent className="p-0">
          {loading ? (
            <div className="flex items-center justify-center py-20">
              <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
            </div>
          ) : payments.length === 0 ? (
            <div className="text-center py-12">
              <Banknote className="w-10 h-10 text-muted-foreground mx-auto mb-3" />
              <p className="text-muted-foreground">No payments received yet.</p>
              <p className="text-sm text-muted-foreground mt-1">Payments will appear here once your employer runs payroll.</p>
            </div>
          ) : (
            <>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="pl-6">Date</TableHead>
                    <TableHead>Amount</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead className="w-12"></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {payments.map((p: any) => (
                    <TableRow key={p._id}>
                      <TableCell className="text-sm pl-6">
                        {new Date(p.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
                      </TableCell>
                      <TableCell className="font-mono text-sm font-medium">
                        ${p.amount ? parseFloat(p.amount).toFixed(2) : "0.00"}
                      </TableCell>
                      <TableCell>
                        <Badge
                          variant={p.status === "COMPLETED" ? "default" : p.status === "FAILED" ? "destructive" : "secondary"}
                          className="text-xs"
                        >
                          {p.status}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        {p.status === "COMPLETED" && (
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => downloadPayslip(p._id)}
                            className="text-muted-foreground hover:text-foreground"
                          >
                            <Download className="w-4 h-4" />
                          </Button>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
              {totalPages > 1 && (
                <div className="flex items-center justify-between px-4 py-3 border-t border-border">
                  <Button variant="ghost" size="sm" onClick={() => setPage(Math.max(1, page - 1))} disabled={page === 1}>
                    <ChevronLeft className="w-4 h-4 mr-1" /> Previous
                  </Button>
                  <span className="text-sm text-muted-foreground">Page {page} of {totalPages}</span>
                  <Button variant="ghost" size="sm" onClick={() => setPage(page + 1)} disabled={page >= totalPages}>
                    Next <ChevronRight className="w-4 h-4 ml-1" />
                  </Button>
                </div>
              )}
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
